[project]
name = "azure-sql-mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-identity>=1.23.0",
    "azure-mgmt-resource==23.4.0",
    "azure-mgmt-sql==3.0.1",
    "mcp[cli]>=1.9.4",
]
